/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for *Check, Please* checklists
 */
export interface Checklist {
  /**
   * Address or other string identifying the person who is requesting completion of this checklist
   */
  requester?: string;
  /**
   * Address or other string identifying the person who should execute this checklist
   */
  executor: string;
  /**
   * Description of the checklist
   */
  description?: string;
  /**
   * Steps to be executed
   */
  steps?: Step[];
}
export interface Step {
  /**
   * Chain ID for network that transaction should be executed on
   */
  chain_id: string;
  /**
   * To address for the transaction
   */
  to: string;
  /**
   * Amount of wei (lowest denomination of native token) to send with the transaction
   */
  value?: string;
  /**
   * Calldata for the transaction
   */
  calldata?: string;
  /**
   * ABI for the method to be called - this can be used to contextualize the calldata
   */
  method_abi?: {
    [k: string]: unknown;
  };
  /**
   * Description of the step
   */
  description?: string;
  /**
   * Hash of the transaction that was executed for this step
   */
  tx_hash?: string;
}
